### ISSUE TITLE
Спасибо за бота по валютам.

### ISSUE THREAD

**Issue by dmp40** [alenapoliakova/CurrencyRateTgBot#2]
Только начинаю изучать Python. Бота запустил - все работает. 
Для меня это пока космос.
Полезно было узнать как хранить токен запускать нужные пакеты.

Делаю себе простого бота, который должен провести тест по гибкости.
Ранее делал такого в сервисе ботов ManyChat.
Теперь пытаюсь повторить и запутался в обработке нажатий клавиатуры.

**Comment by alenapoliakova** [comment]
Токен для бота нельзя выкладывать в открытый доступ, поэтому его можно хранить в переменном окружение для проекта с ботом. Для этого нужно создать в проекте файл **.env** и поместить туда токен для бота:
`BOT_TOKEN=123456:Your-Token_Example`

Далее, чтобы считать токен из переменного окружения, в файле, где вы создаёте бота, введите:
```
from environs import Env

env = Env()
env.read_env()
BOT_TOKEN = env("BOT_TOKEN")
```
И вы сможете использовать переменную BOT_TOKEN для создания бота в вашем проекте.

Также не забудьте добавить в **gitignore** файл .env (чтобы его не увидели другие пользователи). Для этого создаётся ещё один файл .gitignore:
`.env`

**Comment by alenapoliakova** [comment]
Про вопрос, как запускать нужные пакеты, я не поняла в чём суть вопроса)

Про клавиатуру в pyTelegramBotAPI можно почитать [тут](https://github.com/eternnoir/pyTelegramBotAPI) в разделе Reply markup.

**Comment by dmp40** [comment]
Вопроса не было). Мне понравилось, что все нужные пакеты прописаны в одно м файле  и  устаавливаются одной командой.
Про токены тоже все понятно. Спасибо!!!
Пока сохранил  в файле settings.py. 
За ссылку про клавиатуру спасибо.  Разбираюсь по-тихоньку. Если можно , позже покажу код и спрошу конкретнее.
Лет 30 не программировал и идет не так легко, как ожидал.

**Comment by alenapoliakova** [comment]
> Если можно , позже покажу код и спрошу конкретнее.

Хорошо

**Comment by dmp40** [comment]
Вот сделал шаблон бота https://gist.github.com/dmp40/c6ce4d0fd8cc153ea62ef5aca7ff0267
Бот должен показать пользователю 5 упражнений на гибкость.
После каждого видео пользователь выбирает, что у него получилось и нажимает одну из трех клавиш,
Затем кнопка ДАЛЕЕ и выводится новое упражнение.
Почему-то после нажатия ДАЛЕЕ ничего не происходит.
Какая-то мелочь. Не могу понять какая. Помогие, пожалуйста

**Comment by dmp40** [comment]
https://gist.github.com/dmp40/c6ce4d0fd8cc153ea62ef5aca7ff0267
iшаблон бота
